# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/docker/php-fpm/" # Location of package manifests
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
      day: "saturday"
      time: "05:00"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major","version-update:semver-minor"]

  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/docker/nginx/" # Location of package manifests
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
      day: "saturday"
      time: "05:00"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/docker/ipref3/" # Location of package manifests
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
      day: "saturday"
      time: "05:00"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]


  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
      day: "saturday"
      timezone: "Europe/Berlin"
      time: "05:00"
