name: Tools - Docker Build Test

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  docker-build-image:
    name: Docker Build Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - image: wydler/lookingglass-web
            dockerfile: ./docker/nginx/Dockerfile
          - image: wydler/lookingglass-php
            dockerfile: ./docker/php-fpm/Dockerfile
          - image: wydler/lookingglass-iperf
            dockerfile: ./docker/ipref3/Dockerfile
       
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: ${{ matrix.image }}

      - name: Build docker images
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64/v8
     
