name: "Tools - Validate Dockerfile Schema"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  validate-dockerfile-schema:
    name: Haskell Linter
    runs-on: ubuntu-latest

    permissions:
      contents: read
      
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 #v3.3.0
        with:
          dockerfile: Dockerfile
          recursive: true
          ignore: "DL3008,DL3015,DL3018"
