---
version: "3.9"

services:
  web:
    image: "wydler/lookingglass-web:${DOCKER_HUB_CONTAINER_TAG}"
    container_name: "lookingglass_www"
    restart: "unless-stopped"
    ports:
      - "80:80"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

      - "./data/nginx/logs:/var/log/nginx:rw"
      - "./data/webapp:/var/www/html:rw"
      - "./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf:rw"
    env_file:
      - .env
    links:
      - php-fpm
    networks:
      frontend:


  php-fpm:
    image: "wydler/lookingglass-php:${DOCKER_HUB_CONTAINER_TAG}"
    container_name: "lookingglass_php-fpm"
    restart: "unless-stopped"
    user: "33:33"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

      - "./data/php-fpm/logs:/var/log:rw"
      - "./conf/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw"
      - "./data/webapp:/var/www/html:rw"
    networks:
      frontend:


  iperf:
    image: "wydler/lookingglass-iperf:${DOCKER_HUB_CONTAINER_TAG}"
    container_name: "lookingglass_iperf"
    restart: "unless-stopped"
    ports:
      - "5201:5201/tcp"
      - "5201:5201/udp"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      frontend:


networks:
  frontend:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd00:cafe:face:feed::/64

