name: Build & publish docker images (master)
on:
  workflow_dispatch:
#  push:
#    branches:
#      - 'master'
#    tags-ignore:
#      - '**'
#    paths-ignore:
#      - 'README.md'
#      - '.github/workflows/**'


jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: wydler/lookingglass-web
            dockerfile: ./docker/nginx/Dockerfile
          - image: wydler/lookingglass-php
            dockerfile: ./docker/php-fpm/Dockerfile
          - image: wydler/lookingglass-iperf
            dockerfile: ./docker/ipref3/Dockerfile
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64/v8
