---
name: Tools - Renovate

"on":
  schedule:
    - cron: "0 5 * * 6"  # Jeden Samstag um 05:00 Uhr
  workflow_dispatch:
    inputs:
      logLevel:
        type: choice
        required: false
        options:
          - info
          - debug
        default: "info"


permissions:
  contents: write
  pull-requests: write
  issues: write


jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate app token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1  # v3.2.0
        id: generate-token
        with:
          client-id: ${{ secrets.GH_APP_RDP_ID }}
          private-key: ${{ secrets.GH_APP_RDP_PRIVATE_KEY }}

      - name: Run Renovate
        uses: renovatebot/github-action@22e0a16091fc706b04affe6ae53d5e3358ac4023  # v46.1.19
        with:
          token: ${{ steps.generate-token.outputs.token }}
          # token: ${{ secrets.GH_TOKEN }}
        env:
          LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
          # Repository taken from variable to keep configuration file generic
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          # This flag will stop renovate from trying to create an onboarding PR, instead it will look for renovate.json file and run
          RENOVATE_ONBOARDING: "false"
          RENOVATE_DEPENDENCY_DASHBOARD_AUTOCLOSE: "true"
          RENOVATE_DEPENDENCY_DASHBOARD_TITLE: "Renovate Dependency Dashboard"
